 wordpress:
   replicaCount: 3
   image: wordpress
   resources:
     limits:
       cpu: 500m
       memory: 800Mi
     requests:
       cpu: 200m
       memory: 600Mi
   service:
     type: NodePort
     port: 80
   livenessProbe:
     httpGet:
       path: /
       port: 80
     initialDelaySeconds: 10
     periodSeconds: 10
   readinessProbe:
     httpGet:
       path: /
       port: 80
     initialDelaySeconds: 5
     periodSeconds: 5
 
 database:
   enabled: true
   type: mysql
   replicaCount: 1
   image: mysql:5.7
   persistence:
     enabled: true
     storageClass: "standard"
     accessModes:
       - ReadWriteOnce
     size: 10Gi
   resources:
     limits:
       cpu: 1000m
       memory: 1Gi
     requests:
       cpu: 500m
       memory: 800Mi
   livenessProbe:
     tcpSocket:
       port: 3306
     initialDelaySeconds: 10
     periodSeconds: 10
   readinessProbe:
     tcpSocket:
       port: 3306
     initialDelaySeconds: 5
     periodSeconds: 5
   auth:
     username: "keepcoding"
     password: "123456"
     rootPassword: "123456" 
 
 service:
   port: 80
 
 ingress:
   enabled: false
   hostname: wordpress.local
 
 autoscaling:
   enabled: true
   minReplicas: 2
   maxReplicas: 5
   targetCPUUtilizationPercentage: 70