apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql.default.svc.cluster.local"
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: {{ .Values.wordpress.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wordpress.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: {{ .Values.wordpress.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wordpress.livenessProbe.periodSeconds }}
          resources:
            limits:
              cpu: {{ .Values.wordpress.resources.limits.cpu }}
              memory: {{ .Values.wordpress.resources.limits.memory }}
            requests:
              cpu: {{ .Values.wordpress.resources.requests.cpu }}
              memory: {{ .Values.wordpress.resources.requests.memory }}
