apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.database.auth.username | b64enc }}
  password: {{ .Values.database.auth.password | b64enc }}
  root-password: {{ .Values.database.auth.rootPassword | b64enc }}
